# Generated by Django 4.2 on 2023-04-23 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modalidade', models.CharField(max_length=100)),
                ('campeonato', models.CharField(max_length=100)),
                ('mandante', models.CharField(max_length=100)),
                ('visitante', models.CharField(max_length=100)),
                ('placar_mandante', models.IntegerField()),
                ('placar_visitante', models.IntegerField()),
                ('odd_vitoria', models.FloatField()),
                ('odd_empate', models.FloatField()),
                ('odd_derrota', models.FloatField()),
                ('num_bets', models.IntegerField()),
                ('chance_mandante', models.FloatField()),
                ('chance_visitante', models.FloatField()),
                ('img_mandante', models.CharField(max_length=100)),
                ('img_visitante', models.CharField(max_length=100)),
            ],
        ),
    ]
